[package]
name = "flatkvm-paste"
version = "0.1.1"
authors = ["Sergio Lopez <slp@sinrega.org>"]
edition = "2018"

[dependencies]
clap = "2.32.0"

x11-clipboard = { git = "https://github.com/flatkvm/x11-clipboard" }
